---
- hosts: all
  tasks:
   - name: Install 7zip from the exe
     win_package:
       path: C:\Users\Admin\Downloads\7z2106-x64.exe
       creates_path: C:\Program Files\7-Zip\7z.exe
       creates_version: 21.06
       state: present
